add doc on OpenAPI build workflow
opengeospatial/ogcapi-maps pull request #90
Opened 2022-05-02 23:44 UTC by tomkralidis

Adds/updates build instructions (consistent to https://github.com/opengeospatial/ogcapi-coverages/blob/master/standard/openapi/README.md)

cc @jerstlouis

2022-05-02 23:57 UTC, jerstlouis requested changes

2022-05-02 23:57 UTC, jerstlouis commented on openapi/README.md
> +This example API definition can be used to provide an OpenAPI 3.0 definition for an implementation of _OGC API - Maps.
This breaks the italic, could you please remove this line change?

2022-05-03 00:05 UTC, tomkralidis commented on openapi/README.md
> +This example API definition can be used to provide an OpenAPI 3.0 definition for an implementation of _OGC API - Maps.
Fixed.

2022-05-03 00:15 UTC, jerstlouis commented
Thanks @tomkralidis .
I don't have merge rights currently on this repo, so cc'ing @joanma747 .

2022-05-12 10:26 UTC, tomkralidis commented
Thanks @jerstlouis; @joanma747 let me know if there are any updates required.

2022-06-13 11:04 UTC, jerstlouis commented
@tomkralidis There doesn't seem to be any GitHub action included in this PR, is something missing?

2022-06-13 14:39 UTC, tomkralidis commented
@jerstlouis the initial PR was for dev workflow.  Good point, GitHub Actions workflows now added.

2022-06-13 14:43 UTC, jerstlouis commented
@tomkralidis Thanks Tom! cc @joanma747

2022-07-14 15:33 UTC, merged